### ISSUE TITLE
How to provide context for markup

### ISSUE THREAD

**Issue by loominade** [kss-node/kss-node#235]
For some elements I need to provide some context, like a certain background color. That of course should not be in the documentation because its not a part of the component.

![example](https://cloud.githubusercontent.com/assets/11677380/10130412/c9056886-65c8-11e5-988e-73bfaf32f721.png)

Is there a way to provide CSS context for certain elements?

**Comment by JohnAlbin** [comment]
I have a kss-only.scss file that generates CSS that I only include in the style guide and not in my app.

The kss template has plenty of IDs or class selectors that you can attach custom CSS to. e.g.

```scss
[id^="kssref-layouts-"] [class^="layout-"][class*="__"] {
  outline: 1px dotted color('grey');
}
```
