### ISSUE TITLE
BEM methodology

### ISSUE THREAD

**Issue by 0x6a68** [kss-node/kss-node#31]
has somebody experience on implementing this into kss?

e.g.

``` scss
// Buttons
// 
// some nice description
//
// Markup:
// <a href="#" class="button{$modifiers}">Button (a.button)</a>
//
// --primary

.button {
 padding: 25em;
 background-color: acolor;
}

.button--primary {
  @extend .button;
  background-color: another;
}
```

So what will be generated here? 

the {#modifierMarkup} for default will be: 

``` html
<a href="#" class="button{$modifiers}">Button (a.button)</a>
```

`button--primary` looks nice and i am happy! but for the default a class will be generated `button{$modifiers}`, that has no styles of course. does anybody know how to handle with this?
