### ISSUE TITLE
hover pseudo class is not generated

### ISSUE THREAD

**Issue by MartinMuzatko** [kss-node/kss-node#396]
Hello! I'm using LESS to create and manage my styles.

Do I have to generate the pseudo selectors on my own? because KSS does not pick up my component using a mixin which defines the :hover state.
However, in the processed CSS, there is the correct pseudo selector (e.g.: `.button:hover{}`)

Is there something that I missed?

**Comment by RobLoach** [comment]
Could you provide a CSS sample test case to test this? Thanks!

**Comment by MartinMuzatko** [comment]
Sure!

```css
.button-primary:hover,
.button-primary:visited:hover {
    background-color:#a4cc6b;
    border:1px solid #a4cc6b;
    color:#3b4;
}
```
