### ISSUE TITLE
Include stylesheet source code into styleguide

### ISSUE THREAD

**Issue by indieveed** [kss-node/kss-node#50]
May be i just did not figure out this thing, but is it possible to output source code (CSS, SASS, LESS). There are only html outputs in examples, but i would like to show my source code too. I know that syledocco can do this. Is it possible with kss-node?
If not, it could be a good feature.

**Comment by erfanimani** [comment]
Github's styleguide has something similar to what's being requested in this issue: http://primercss.io/colors/

But, unfortunately, theirs doesn't seem to be automatically generated either: https://raw.githubusercontent.com/primer/primer/master/docs/colors.md

**Comment by vidhill** [comment]
I'm just going to add this as a reference for others looking into this, 

The project **[sc5-styleguidess](https://github.com/SC5/sc5-styleguide)** use [gonzales-pe](https://github.com/tonyganch/gonzales-pe) in combination with [gonzales-ast](https://github.com/stoyan/gonzales-ast) to parse sass sourse.

Their source is [here](https://github.com/varya/sc5-styleguide/blob/2ce75a64970eda054ff1f59475e0b529117a33e1/lib/modules/kss-splitter.js) 
- info via @varya

**Comment by tsi** [comment]
This is my work-around for a color list, it's far from perfect, and I have to maintain 2 lists, but it works.

```scss

// Colors
//
// #97007A - : Magenta
// #424344 - : Grey
// #28292A - : Dark grey
//
// Markup: <div style="background: {{modifier_class}};" class="styleguide-color">{{modifier_class}}</div>
//
// Styleguide 1

$color--magenta: #97007A;
$color--grey: #424344;
$color--grey-dark: #28292A;

```
