### ISSUE TITLE
Problems with generation guides of SCSS-mixins

### ISSUE THREAD

**Issue by lancedikson** [kss-node/kss-node#68]
Hi! Help me, please.
I have this code:

``` scss
// Yellow gradient
//
// Compatible in IE6+, Firefox 2+, Safari 4+.
@mixin gr-yellow() {
    background:-webkit-linear-gradient(#FEE789, #FCCD10);
    background:     -o-linear-gradient(#FEE789, #FCCD10);
    background:linear-gradient(#FEE789, #FCCD10);
}
```

And this block don't exist in generated documentation. What I'm doing wrong?
