### ISSUE TITLE
Examples in top-level sections do not display

### ISSUE THREAD

**Issue by wachunga** [kss-node/kss-node#8]
When you don't need subsections, it would be nice to be able to include examples right in your top-level section.

For example:

``` css
/*
Bins

Generic enclosed containers

Markup:
<div class="bin {$modifiers}">content</div>

Styleguide 6
*/

.bin {
     background-color: #ccc;
     border: 1px solid #333;
     margin-bottom: 10px;
     padding: 10px;
}
```
